clixon_beh: Hack to fix a python issue
Running on yocto I'm getting an error:

ImportError: cannot import name '_cclixon' from partially initialized
module 'clixon_beh' (most likely due to a circular import)
(/usr/lib64/python3.10/clixon_beh/__init__.py)

which doesn't happen on ubuntu.  This hack seems to fix the issue,
though I'm not sure why.

Signed-off-by: Corey Minyard <cminyard@mvista.com>